version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspaces/homeassistant-homevolt
    env_file:
      - .devcontainer/devcontainer.env
    command: sleep infinity
    ports:
      - "8123:8123"  # Home Assistant web interface
    environment:
      - PYTHONPATH=/workspaces/homeassistant-homevolt