#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Activate virtual environment if it exists
if [ -d ".venv" ]; then
    source .venv/bin/activate
fi

# Create config dir if not present
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Set the path to custom_components
# This lets us have the structure we want <root>/custom_components/homevolt_local
# while at the same time have Home Assistant configuration inside <root>/config
# without resorting to symlinks.
export PYTHONPATH="${PWD}/custom_components${PYTHONPATH:+:$PYTHONPATH}"

# Start Home Assistant
hass --config "${PWD}/config" --debug
